services:
  db:
    image: postgres:16
    container_name: pg_crud
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  db_seed:
    image: postgres:16
    container_name: pg_seed
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DB_HOST: ${DB_HOST}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./scripts-init:/scripts-init
      - ./scripts-init/entrypoint.sh:/entrypoint.sh
    entrypoint: ["bash", "/entrypoint.sh"]
    restart: "no"

  backend:
    build: ./backend
    container_name: api_crud
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${PORT}:3000"
    restart: unless-stopped
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: web_crud
    depends_on:
      - backend
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  pgdata:

networks:
  default:
    name: app_network
